export const imageProfileUrl =
  'https://firebasestorage.googleapis.com/v0/b/profile-website-1.appspot.com/o/profile_image.jpg?alt=media&token=a8873dbf-530b-43a0-a59a-0f7724af1919'
export const githubUrl = 'https://github.com/newtrn'
export const githubText = 'github.com/newtrn'
export const codepenUrl = 'https://codepen.io/dodosike'
export const codepenText = 'codepen.io/dodosike'
export const facebookUrl = 'https://www.facebook.com/suppawit.satitsongtam'
export const facebookText = 'facebook.com/suppawit.satitsongtam'
export const igUrl = 'https://www.instagram.com/nueclears/'
export const igText = 'instagram.com/nueclears/'
export const twitterUrl = 'https://twitter.com/suppawitnw'
export const twitterText = 'twitter.com/suppawitnw'
export const email = 't_ongyod@hotmail.com'
export const homeUrl = 'https://goo.gl/maps/X5HXW5PLEaAhjGNg8'
export const homeText = 'Bangkok, Bangbon'
export const birthday = '28 Nov 1996'
export const linkedInUrl = 'https://www.linkedin.com/in/suppawit-satitsongtam-88b1231a3/'
export const linkedInText = 'linkedin.com/suppawit-satitsongtam'
